# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Squanderr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Squanderr
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'Firebase/Storage'



  target 'SquanderrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SquanderrUITests' do
    # Pods for testing
  end

end
